"""Inicializacion de tablas

Revision ID: ee2aa66d2bce
Revises: 
Create Date: 2026-02-16 11:47:38.438063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee2aa66d2bce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('applications', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('applications', 'opportunity_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_applications_created_at'), table_name='applications')
    op.drop_index(op.f('idx_applications_opportunity_id'), table_name='applications')
    op.drop_index(op.f('idx_applications_user_id'), table_name='applications')
    op.drop_constraint(op.f('uq_applications_user_opportunity'), 'applications', type_='unique')
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.drop_constraint(op.f('fk_applications_opportunity'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('fk_applications_user'), 'applications', type_='foreignkey')
    op.create_foreign_key(None, 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'applications', 'opportunities', ['opportunity_id'], ['id'])
    op.alter_column('courses', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('courses', 'opportunity_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('courses', 'content_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.drop_constraint(op.f('courses_opportunity_id_key'), 'courses', type_='unique')
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.drop_constraint(op.f('fk_courses_opportunity'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'opportunities', ['opportunity_id'], ['id'])
    op.drop_column('courses', 'quiz_data')
    op.alter_column('opportunities', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('opportunities', 'company_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('opportunities', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('opportunities', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('opportunities', 'status',
               existing_type=postgresql.ENUM('draft', 'pending_review', 'published', 'closed', name='opportunity_status'),
               type_=sa.Enum('draft', 'pending_review', 'published', 'closed', name='opportunitystatus'),
               nullable=True,
               existing_server_default=sa.text("'pending_review'::opportunity_status"))
    op.drop_index(op.f('idx_opportunities_company_id'), table_name='opportunities')
    op.drop_index(op.f('idx_opportunities_status'), table_name='opportunities')
    op.create_index(op.f('ix_opportunities_id'), 'opportunities', ['id'], unique=False)
    op.drop_constraint(op.f('fk_opportunities_company'), 'opportunities', type_='foreignkey')
    op.create_foreign_key(None, 'opportunities', 'users', ['company_id'], ['id'])
    op.drop_column('opportunities', 'requirements')
    op.add_column('user_progress', sa.Column('id', sa.Integer(), nullable=False))
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('user_progress', 'course_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=True)
    op.alter_column('user_progress', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_user_progress_course_id'), table_name='user_progress')
    op.drop_index(op.f('idx_user_progress_user_completed'), table_name='user_progress')
    op.create_index(op.f('ix_user_progress_id'), 'user_progress', ['id'], unique=False)
    op.drop_constraint(op.f('fk_user_progress_course'), 'user_progress', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_progress_user'), 'user_progress', type_='foreignkey')
    op.create_foreign_key(None, 'user_progress', 'courses', ['course_id'], ['id'])
    op.create_foreign_key(None, 'user_progress', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('student', 'company', 'admin', name='user_role'),
               type_=sa.Enum('student', 'company', 'admin', name='userrole'),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'profile_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('student', 'company', 'admin', name='userrole'),
               type_=postgresql.ENUM('student', 'company', 'admin', name='user_role'),
               nullable=False)
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.drop_constraint(None, 'user_progress', type_='foreignkey')
    op.create_foreign_key(op.f('fk_user_progress_user'), 'user_progress', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_user_progress_course'), 'user_progress', 'courses', ['course_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_progress_id'), table_name='user_progress')
    op.create_index(op.f('idx_user_progress_user_completed'), 'user_progress', ['user_id', 'is_completed'], unique=False)
    op.create_index(op.f('idx_user_progress_course_id'), 'user_progress', ['course_id'], unique=False)
    op.alter_column('user_progress', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('user_progress', 'course_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('user_progress', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.drop_column('user_progress', 'id')
    op.add_column('opportunities', sa.Column('requirements', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'opportunities', type_='foreignkey')
    op.create_foreign_key(op.f('fk_opportunities_company'), 'opportunities', 'users', ['company_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_opportunities_id'), table_name='opportunities')
    op.create_index(op.f('idx_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('idx_opportunities_company_id'), 'opportunities', ['company_id'], unique=False)
    op.alter_column('opportunities', 'status',
               existing_type=sa.Enum('draft', 'pending_review', 'published', 'closed', name='opportunitystatus'),
               type_=postgresql.ENUM('draft', 'pending_review', 'published', 'closed', name='opportunity_status'),
               nullable=False,
               existing_server_default=sa.text("'pending_review'::opportunity_status"))
    op.alter_column('opportunities', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('opportunities', 'title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('opportunities', 'company_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('opportunities', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.add_column('courses', sa.Column('quiz_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('fk_courses_opportunity'), 'courses', 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.create_unique_constraint(op.f('courses_opportunity_id_key'), 'courses', ['opportunity_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('courses', 'content_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('courses', 'opportunity_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('courses', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.create_foreign_key(op.f('fk_applications_user'), 'applications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_applications_opportunity'), 'applications', 'opportunities', ['opportunity_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.create_unique_constraint(op.f('uq_applications_user_opportunity'), 'applications', ['user_id', 'opportunity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_applications_user_id'), 'applications', ['user_id'], unique=False)
    op.create_index(op.f('idx_applications_opportunity_id'), 'applications', ['opportunity_id'], unique=False)
    op.create_index(op.f('idx_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.alter_column('applications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('applications', 'opportunity_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('applications', 'user_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=False)
    op.alter_column('applications', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
